#!/bin/bash

num=$1

if[$num -gt 20]; then
echo "Given number $num is greater  than  20"
fi
#
#if[$num -gt 20]; then
#echo "Given number $num is greater  than  20"
#else
#echo "Given number $num is less  than  20"
#fi


#if[$num -gt 20]; then
#echo "Given number $num is greater  than  20"
#elseif[$num -eq 20]; then
#echo "Given number $num is equal to 20"
#else
#echo "Given number $num is less  than  20"
#fi
#